export const CONSTANTS = {
    SET_POSITION: "SET_POSITION",
    SET_SELECTED_SQUARE: "SET_SELECTED_SQUARE",
    SET_HIGHLIGHTED_SQUARES: "SET_HIGHLIGHTED_SQUARES",
    SET_MOVE_HISTORY: "SET_MOVE_HISTORY",
    SET_CURRENT_MOVE: "SET_CURRENT_MOVE",
    SET_IS_WHITE_TURN: "SET_IS_WHITE_TURN",
    SET_IS_GAME_OVER: "SET_IS_GAME_OVER",
    SET_WINNER: "SET_WINNER",
    SET_MOVE_COUNT: "SET_MOVE_COUNT",
    SET_MOVE_STACK: "SET_MOVE_STACK",
    SET_SUGGESTED_MOVES: "SET_SUGGESTED_MOVES",
    SET_MOVING_PIECE: "SET_MOVING_PIECE",
    SET_IS_CHECKMATE: "SET_IS_CHECKMATE",
};

